INSERT INTO cbp_db_test_v2.PayDraft (PayDraftID, PayMID, Payee, InvoiceNo, SubmarineCable, WorkTitle, CableInfo,
                                     TotalFeeAmount, Subject, Address, CtactPerson, Tel, email, IssueDate, IssueNo,
                                     OriginalTo, CBPBankAcctNo, BankAcctName, BankName, BankAddress, BankAcctNo, IBAN,
                                     SWIFTCode, ACHNo, WireRouting, Status, PayeeType, URI)
VALUES (1,
        1,
        'NEC',
        'DT0170168-1/DT0170168-2',
        'SJC2',
        'Construction',
        '',
        208294.52,
        '',
        '',
        '',
        '',
        '',
        '2023-06-25 08:34:00',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        'TEMPORARY',
        'SUPPLIER',
        '');
