/* Liability */
INSERT INTO cbp_db_test_v2.Liability (LBRawID, SubmarineCable, WorkTitle, BillMilestone, PartyName, LBRatio, CreateDate, Note, ModifyNote, EndDate) VALUES (1, 'SJC2', 'Construction', 'BM9a', 'CM', 28.5714285714, '2023-06-01 17:27:01', '', null, null);
INSERT INTO cbp_db_test_v2.Liability (LBRawID, SubmarineCable, WorkTitle, BillMilestone, PartyName, LBRatio, CreateDate, Note, ModifyNote, EndDate) VALUES (2, 'SJC2', 'Construction', 'BM9a', 'EDGE', 28.5714285714, '2023-06-01 17:27:02', '', null, null);
INSERT INTO cbp_db_test_v2.Liability (LBRawID, SubmarineCable, WorkTitle, BillMilestone, PartyName, LBRatio, CreateDate, Note, ModifyNote, EndDate) VALUES (3, 'SJC2', 'Construction', 'BM9a', 'CHT', 7.1428571429, '2023-06-01 17:27:02', '', null, null);
INSERT INTO cbp_db_test_v2.Liability (LBRawID, SubmarineCable, WorkTitle, BillMilestone, PartyName, LBRatio, CreateDate, Note, ModifyNote, EndDate) VALUES (4, 'SJC2', 'Construction', 'BM9a', 'SKB', 7.1428571429, '2023-06-01 17:27:02', '', null, null);
INSERT INTO cbp_db_test_v2.Liability (LBRawID, SubmarineCable, WorkTitle, BillMilestone, PartyName, LBRatio, CreateDate, Note, ModifyNote, EndDate) VALUES (5, 'SJC2', 'Construction', 'BM9a', 'TICC', 7.1428571429, '2023-06-01 17:27:02', '', null, null);
INSERT INTO cbp_db_test_v2.Liability (LBRawID, SubmarineCable, WorkTitle, BillMilestone, PartyName, LBRatio, CreateDate, Note, ModifyNote, EndDate) VALUES (6, 'SJC2', 'Construction', 'BM9a', 'VNPT', 7.1428571429, '2023-06-01 17:27:02', '', null, null);
INSERT INTO cbp_db_test_v2.Liability (LBRawID, SubmarineCable, WorkTitle, BillMilestone, PartyName, LBRatio, CreateDate, Note, ModifyNote, EndDate) VALUES (7, 'SJC2', 'Construction', 'BM9a', 'DHT', 3.5714285714, '2023-06-01 17:27:02', '', null, null);
INSERT INTO cbp_db_test_v2.Liability (LBRawID, SubmarineCable, WorkTitle, BillMilestone, PartyName, LBRatio, CreateDate, Note, ModifyNote, EndDate) VALUES (8, 'SJC2', 'Construction', 'BM9a', 'Telin', 3.5714285714, '2023-06-01 17:27:02', '', null, null);
INSERT INTO cbp_db_test_v2.Liability (LBRawID, SubmarineCable, WorkTitle, BillMilestone, PartyName, LBRatio, CreateDate, Note, ModifyNote, EndDate) VALUES (9, 'SJC2', 'Construction', 'BM9a', 'Singtel', 7.0634920635, '2023-06-01 17:27:02', '', null, null);
INSERT INTO cbp_db_test_v2.Liability (LBRawID, SubmarineCable, WorkTitle, BillMilestone, PartyName, LBRatio, CreateDate, Note, ModifyNote, EndDate) VALUES (10, 'SJC2', 'Construction', 'BM9a', 'KDDI', 0.0793650793, '2023-06-01 17:27:02', '', null, null);
INSERT INTO cbp_db_test_v2.Liability (LBRawID, SubmarineCable, WorkTitle, BillMilestone, PartyName, LBRatio, CreateDate, Note, ModifyNote, EndDate) VALUES (11, 'SJC2', 'Construction', 'BM12', 'CHT', 7.1428571429, '2023-06-13 15:10:48', '', null, null);
INSERT INTO cbp_db_test_v2.Liability (LBRawID, SubmarineCable, WorkTitle, BillMilestone, PartyName, LBRatio, CreateDate, Note, ModifyNote, EndDate) VALUES (12, 'SJC2', 'Construction', 'BM12', 'CM', 28.5714285714, '2023-06-13 15:10:48', '', null, null);
INSERT INTO cbp_db_test_v2.Liability (LBRawID, SubmarineCable, WorkTitle, BillMilestone, PartyName, LBRatio, CreateDate, Note, ModifyNote, EndDate) VALUES (13, 'SJC2', 'Construction', 'BM12', 'DHT', 3.5714285714, '2023-06-13 15:10:48', '', null, null);
INSERT INTO cbp_db_test_v2.Liability (LBRawID, SubmarineCable, WorkTitle, BillMilestone, PartyName, LBRatio, CreateDate, Note, ModifyNote, EndDate) VALUES (14, 'SJC2', 'Construction', 'BM12', 'EDGE', 28.5714285714, '2023-06-13 15:10:48', '', null, null);
INSERT INTO cbp_db_test_v2.Liability (LBRawID, SubmarineCable, WorkTitle, BillMilestone, PartyName, LBRatio, CreateDate, Note, ModifyNote, EndDate) VALUES (15, 'SJC2', 'Construction', 'BM12', 'KDDI', 0.0793650794, '2023-06-13 15:10:48', '', null, null);
INSERT INTO cbp_db_test_v2.Liability (LBRawID, SubmarineCable, WorkTitle, BillMilestone, PartyName, LBRatio, CreateDate, Note, ModifyNote, EndDate) VALUES (16, 'SJC2', 'Construction', 'BM12', 'Singtel', 7.0634920635, '2023-06-13 15:10:48', '', null, null);
INSERT INTO cbp_db_test_v2.Liability (LBRawID, SubmarineCable, WorkTitle, BillMilestone, PartyName, LBRatio, CreateDate, Note, ModifyNote, EndDate) VALUES (17, 'SJC2', 'Construction', 'BM12', 'SKB', 7.1428571429, '2023-06-13 15:10:48', '', null, null);
INSERT INTO cbp_db_test_v2.Liability (LBRawID, SubmarineCable, WorkTitle, BillMilestone, PartyName, LBRatio, CreateDate, Note, ModifyNote, EndDate) VALUES (18, 'SJC2', 'Construction', 'BM12', 'Telin', 3.5714285714, '2023-06-13 15:10:48', '', null, null);
INSERT INTO cbp_db_test_v2.Liability (LBRawID, SubmarineCable, WorkTitle, BillMilestone, PartyName, LBRatio, CreateDate, Note, ModifyNote, EndDate) VALUES (19, 'SJC2', 'Construction', 'BM12', 'TICC', 7.1428571429, '2023-06-13 15:10:48', '', null, null);
INSERT INTO cbp_db_test_v2.Liability (LBRawID, SubmarineCable, WorkTitle, BillMilestone, PartyName, LBRatio, CreateDate, Note, ModifyNote, EndDate) VALUES (20, 'SJC2', 'Construction', 'BM12', 'VNPT', 7.1428571428, '2023-06-13 15:10:48', '', null, null);

/* Users */
INSERT INTO cbp_db_test_v2.Users (UserIDNo, UserID, UserName, UserCName, Email, Tel, Fax, Mobile, DirectorName, DEmail, DTel, DFax, Company, Address) VALUES (1, 'chang_ty', 'Eva Chang', '張增懿', 'chang_ty@cht.com.tw', '+886-2-2344-3897', '+886-2-2344-5940', '0988576813', 'Hsuan-Lung Liu', 'lsl008@cht.com.tw', '+886-2-2344-3912', '+886-2-2322-5940', 'International Business Group, Chunghwa Telecom Co., Ltd.', 'No. 31 Aikuo E. Rd., Taipei, Taiwan, 106');

/* Suppliers */
INSERT INTO cbp_db_test_v2.Suppliers (SupplierID, SubmarineCable, WorkTitle, SupplierName, CompanyName, BankAcctName, BankAcctNo, SavingAcctNo, SWIFTCode, IBAN, ACHNo, WireRouting, BankName, Branch, BankAddress) VALUES (1, 'SJC2', 'Construction', 'NEC', 'NEC Corporation, Submarine Network Division', 'NEC Corporation', '', '258008', 'SMBCJPJT', '', '', '', 'Sumitomo Mitsui Banking Corporation, Tokyo Main Office (211)', '', '3-2, Marunouchi 1-chome, Chiyoda-ku, Tokyo, Japan NEC Corporation');

/* Parties */
INSERT INTO cbp_db_test_v2.Parties (PartyID, SubmarineCable, WorkTitle, PartyCode, PartyName, CompanyName, Address, Contact, Email, Tel, BankAcctName, BankAcctNo, SavingAcctNo, SWIFTCode, IBAN, ACHNo, WireRouting, BankName, Branch, BankAddress) VALUES (1, 'SJC2', 'Construction', 'CI', 'CHT', 'Chunghwa Telecom Co., Ltd. Network Technology Group', '31, Aikuo East Road, Taipei, Taiwan 106', '黃宏杰', 'hj-hwang@cht.com.tw', '02-28054246', '', '', '', '', '', '', '', '', '', '');
INSERT INTO cbp_db_test_v2.Parties (PartyID, SubmarineCable, WorkTitle, PartyCode, PartyName, CompanyName, Address, Contact, Email, Tel, BankAcctName, BankAcctNo, SavingAcctNo, SWIFTCode, IBAN, ACHNo, WireRouting, BankName, Branch, BankAddress) VALUES (2, 'SJC2', 'Construction', 'CM', 'CM', 'China Mobile International Limited Transmission Engineering Manager | Planning & Development', 'Level 30, Tower 1, Kowloon Commerce Centre, No.51 Kwai Cheong Road, Kwai Chung, New Territories, Hong Kong', '黄明华', 'anthonywong@cmi.chinamobile.com', '+852 67656790', '', '', '', '', '', '', '', '', '', '');
INSERT INTO cbp_db_test_v2.Parties (PartyID, SubmarineCable, WorkTitle, PartyCode, PartyName, CompanyName, Address, Contact, Email, Tel, BankAcctName, BankAcctNo, SavingAcctNo, SWIFTCode, IBAN, ACHNo, WireRouting, BankName, Branch, BankAddress) VALUES (3, 'SJC2', 'Construction', 'DH', 'DHT', 'Donghua Telecom Co. Ltd.', 'UNIT A, 7/F, TOWER A, BILLION CENTRE, NO.1 WANG KWONG ROAD, KOWLOON BAY, KOWLOON, HKSAR', 'Frankie', 'frankie@donghwatele.com', '+852-35862600', '', '', '', '', '', '', '', '', '', '');
INSERT INTO cbp_db_test_v2.Parties (PartyID, SubmarineCable, WorkTitle, PartyCode, PartyName, CompanyName, Address, Contact, Email, Tel, BankAcctName, BankAcctNo, SavingAcctNo, SWIFTCode, IBAN, ACHNo, WireRouting, BankName, Branch, BankAddress) VALUES (4, 'SJC2', 'Construction', 'EG', 'EDGE', 'Edge Network Services Limited', '4 Grand Canal Square, Dublin 2, Ireland', 'Nicholas', 'nictanch@fb.com', '+85295384781', '', '', '', '', '', '', '', '', '', '');
INSERT INTO cbp_db_test_v2.Parties (PartyID, SubmarineCable, WorkTitle, PartyCode, PartyName, CompanyName, Address, Contact, Email, Tel, BankAcctName, BankAcctNo, SavingAcctNo, SWIFTCode, IBAN, ACHNo, WireRouting, BankName, Branch, BankAddress) VALUES (5, 'SJC2', 'Construction', 'KD', 'KDDI', 'KDDI Corporation Global Network Engineering and Operations Center (GNOC)', 'KDDI Bldg., 2-3-2, Nishishinjuku, Shinjuku-ku, Tokyo 163-8003, Japan', 'Mr. Koki Takeshima', 'gnoc-cable@kddi.com', '+81-3-3347-6064', '', '', '', '', '', '', '', '', '', '');
INSERT INTO cbp_db_test_v2.Parties (PartyID, SubmarineCable, WorkTitle, PartyCode, PartyName, CompanyName, Address, Contact, Email, Tel, BankAcctName, BankAcctNo, SavingAcctNo, SWIFTCode, IBAN, ACHNo, WireRouting, BankName, Branch, BankAddress) VALUES (6, 'SJC2', 'Construction', 'ST', 'Singtel', 'Singapore Telecommunications Limited', 'COM3, #06-01, 31C Exeter Road Singapore 239734', 'Yue Meng Fai', 'mengfai@singtel.com', '+65 68872921', '', '', '', '', '', '', '', '', '', '');
INSERT INTO cbp_db_test_v2.Parties (PartyID, SubmarineCable, WorkTitle, PartyCode, PartyName, CompanyName, Address, Contact, Email, Tel, BankAcctName, BankAcctNo, SavingAcctNo, SWIFTCode, IBAN, ACHNo, WireRouting, BankName, Branch, BankAddress) VALUES (7, 'SJC2', 'Construction', 'SK', 'SKB', 'SK Broadband Co., Ltd. (SKB)', '8F, SK Namsan Green Bldg., 24, Toegye-ro, Jung-gu, Seoul 04637, Korea', 'SUN JIN KUK (Chris)', 'chris.sun@sk.com', '+82-10-3702-0461', '', '', '', '', '', '', '', '', '', '');
INSERT INTO cbp_db_test_v2.Parties (PartyID, SubmarineCable, WorkTitle, PartyCode, PartyName, CompanyName, Address, Contact, Email, Tel, BankAcctName, BankAcctNo, SavingAcctNo, SWIFTCode, IBAN, ACHNo, WireRouting, BankName, Branch, BankAddress) VALUES (8, 'SJC2', 'Construction', 'TE', 'Telin', 'PT. Telekomunikasi Indonesia International (Telin) Digital & Service Planning and Development', 'Telkom Landmark Tower (TLT), Tower 2, 16thand 17th Floor,  Jalan Jendral Gatot Subroto, Kavling 52,Jakarta Selatan, Indonesia 12710', 'Mr. Edward Natanael', 'edward.natanael@telin.net', '+62 21 2995 2300', '', '', '', '', '', '', '', '', '', '');
INSERT INTO cbp_db_test_v2.Parties (PartyID, SubmarineCable, WorkTitle, PartyCode, PartyName, CompanyName, Address, Contact, Email, Tel, BankAcctName, BankAcctNo, SavingAcctNo, SWIFTCode, IBAN, ACHNo, WireRouting, BankName, Branch, BankAddress) VALUES (9, 'SJC2', 'Construction', 'TC', 'TICC', 'True Internet Corporation Co., Ltd (TICC) International Gateway Business', '18, True Tower, Ratchadapisek Road, Huai Khwang, Bangkok 10310, Thailand', 'Wachira Parathum', 'wachira_par@trueintergateway.com', '+669 5651 5394', '', '', '', '', '', '', '', '', '', '');
INSERT INTO cbp_db_test_v2.Parties (PartyID, SubmarineCable, WorkTitle, PartyCode, PartyName, CompanyName, Address, Contact, Email, Tel, BankAcctName, BankAcctNo, SavingAcctNo, SWIFTCode, IBAN, ACHNo, WireRouting, BankName, Branch, BankAddress) VALUES (10, 'SJC2', 'Construction', 'VN', 'VNPT', 'VNPT NET Corporation (VNPT-NET)', 'Level 10, VNPT Net Building International Network Development Division 30 Pham Hung Street, My Dinh 1 Ward, Nam Tu Liem District, Hanoi, Vietnam', 'Minh Hien', 'nguyenthiminhhien@vnpt.vn', '+84 912312598', '', '', '', '', '', '', '', '', '', '');

