ALTER TABLE BillMaster AUTO_INCREMENT = 1;
ALTER TABLE BillDetail AUTO_INCREMENT = 1;
ALTER TABLE CB AUTO_INCREMENT = 1;
ALTER TABLE CBStatement AUTO_INCREMENT = 1;
ALTER TABLE CollectStatement AUTO_INCREMENT = 1;
ALTER TABLE InvoiceDetail AUTO_INCREMENT = 1;
ALTER TABLE InvoiceMaster AUTO_INCREMENT = 1;